### PR TITLE
Updating GCMConnection so it uses the api key in an authorization header

### PR DESCRIPTION
**Pull request by bradmontgomery**
This is the PR for #11. The test suite for the apn modules failed for me, but the gcm-related tests pass.

Let me know what you think.

### CODE REVIEW

**Comment by dgilland** [comment]
Looks good! Thanks for the bug fix!

Curious, though, what failed for the APNS module?

**Comment by bradmontgomery** [comment]
Thanks! :+1:

**Comment by bradmontgomery** [comment]
@dgilland The full output from the test suite is here: https://gist.github.com/bradmontgomery/3e5721494efd2e525e70

Run on OS X Yosemite under python 3.4.

**Comment by dgilland** [comment]
Thanks for the traceback.

Looks to be related to the socketserver that's run in a separate thread during those tests. It looks like some tests pass but an exception occurs in the serve forever loop. And then for the apns error handler tests, there's a timeout when reading from the socketserver.

Not sure why this is happening on your machine. It's not happening on my Linux server or TravisCI. I don't have access to a Mac environment on I'm not able to reproduce this. Not sure if it's something that can be addressed in the socketserver fixture or if it's an environment issue.

**Comment by bradmontgomery** [comment]
It could be an environment issue. I haven't had a chance to dig into it, but it was a little surprising (could be a barrier to contributions?). Is it worth a new issue? I may have time to dig into it in a few days.

**Comment by dgilland** [comment]
If you're willing to put some time into this, then go ahead and open an issue for it. I'm also not attached to the current implementation that runs the test socketserver so if there's a better way that doesn't have this issue, then I'm fine with it being replaced.

Thanks for taking the time to look into this! :+1:

**Pull request merged**
